/*
 * AddGroupEvent.java
 *
 * Created on 27. duben 2009, 16:29
 */
package dialogs;
import java.util.*;
import client.*;
import COMMON.*;
import java.util.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.table.*;
import javax.swing.border.*;
import javax.swing.JOptionPane;

import javax.swing.JOptionPane;

/**
 *
 * @author  ivo
 */
public class AddGroupEvent extends javax.swing.JDialog {

     /** Creates new form AddGroupEvent */
     public AddGroupEvent(java.awt.Frame parent, boolean modal, String user) {
	  super(parent, modal);
	  initComponents();
	  jLabel1.setText("Date:");
	  jLabel2.setText("Name:");
	  jLabel3.setText("How often:");
	  jTextField2.setText("new_event");
	  jLabel4.setText("Category:");
	  jLabel5.setText("h");
	  jLabel8.setText("d");
	  jLabel6.setText("");
	  jLabel9.setText("h");
	  jLabel10.setText("d");
	  jLabel7.setText("");
	  jLabel11.setText("m");
	  jLabel12.setText("y");
	  jLabel13.setText("Repeatable:");
	  jRadioButton1.setText("Yes");
	  jRadioButton2.setText("No");
	            jRadioButton2.setSelected(true);
	  jLabel14.setText("Group:");
	  jButton2.setText("Confirm");
	  jButton1.setText("Close");
	  this.jComboBox1.removeAllItems();
	  this.jComboBox1.addItem("MEETING");
	  this.jComboBox1.addItem("TASK");
	  this.jComboBox1.addItem("ANNIVERSARY");
	  this.jComboBox1.addItem("OTHER");
	  this.jComboBox2.removeAllItems();
	  LocalCache lc = LocalCache.getDefaultCache();
	  for (Group_membership m : lc.getUser(user).get_groups()) 
	   if ( lc.getGroup(m.get_group_name()).get_boss().equals(user) )
        	  this.jComboBox2.addItem(m.get_group_name());
	  
	  
	  pack();


     }

     /** This method is called from within the constructor to
      * initialize the form.
      * WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {
          java.awt.GridBagConstraints gridBagConstraints;

          buttonGroup1 = new javax.swing.ButtonGroup();
          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jTextField2 = new javax.swing.JTextField();
          jLabel4 = new javax.swing.JLabel();
          jPanel1 = new javax.swing.JPanel();
          jLabel5 = new javax.swing.JLabel();
          jSpinner2 = new javax.swing.JSpinner();
          jLabel8 = new javax.swing.JLabel();
          jSpinner4 = new javax.swing.JSpinner();
          jLabel6 = new javax.swing.JLabel();
          jSpinner3 = new javax.swing.JSpinner();
          jLabel7 = new javax.swing.JLabel();
          jSpinner1 = new javax.swing.JSpinner();
          jPanel2 = new javax.swing.JPanel();
          jLabel9 = new javax.swing.JLabel();
          jSpinner6 = new javax.swing.JSpinner();
          jLabel10 = new javax.swing.JLabel();
          jSpinner7 = new javax.swing.JSpinner();
          jLabel11 = new javax.swing.JLabel();
          jSpinner8 = new javax.swing.JSpinner();
          jLabel12 = new javax.swing.JLabel();
          jSpinner9 = new javax.swing.JSpinner();
          jLabel13 = new javax.swing.JLabel();
          jComboBox1 = new javax.swing.JComboBox();
          jPanel3 = new javax.swing.JPanel();
          jRadioButton1 = new javax.swing.JRadioButton();
          jRadioButton2 = new javax.swing.JRadioButton();
          jLabel14 = new javax.swing.JLabel();
          jComboBox2 = new javax.swing.JComboBox();
          jPanel4 = new javax.swing.JPanel();
          jButton2 = new javax.swing.JButton();
          jButton1 = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
          setName("Form"); // NOI18N
          getContentPane().setLayout(new java.awt.GridBagLayout());



          jLabel1.setName("jLabel1"); // NOI18N
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 0;
          gridBagConstraints.gridy = 1;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
          getContentPane().add(jLabel1, gridBagConstraints);


          jLabel2.setName("jLabel2"); // NOI18N
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 0;
          gridBagConstraints.gridy = 0;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
          getContentPane().add(jLabel2, gridBagConstraints);


          jLabel3.setName("jLabel3"); // NOI18N
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 0;
          gridBagConstraints.gridy = 3;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
          getContentPane().add(jLabel3, gridBagConstraints);


          jTextField2.setName("jTextField2"); // NOI18N
          jTextField2.setPreferredSize(new java.awt.Dimension(120, 23));
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 1;
          gridBagConstraints.gridy = 0;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
          getContentPane().add(jTextField2, gridBagConstraints);


          jLabel4.setName("jLabel4"); // NOI18N
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 0;
          gridBagConstraints.gridy = 4;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
          getContentPane().add(jLabel4, gridBagConstraints);

          jPanel1.setName("jPanel1"); // NOI18N


          jLabel5.setName("jLabel5"); // NOI18N
          jPanel1.add(jLabel5);

          jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
          jSpinner2.setName("jSpinner2"); // NOI18N
          jPanel1.add(jSpinner2);


          jLabel8.setName("jLabel8"); // NOI18N
          jPanel1.add(jLabel8);

          jSpinner4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));
          jSpinner4.setName("jSpinner4"); // NOI18N
          jPanel1.add(jSpinner4);


          jLabel6.setName("jLabel6"); // NOI18N
          jPanel1.add(jLabel6);

          jSpinner3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 11, 1));
          jSpinner3.setName("jSpinner3"); // NOI18N
          //jPanel1.add(jSpinner3);


          jLabel7.setName("jLabel7"); // NOI18N
          jPanel1.add(jLabel7);

          jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 2020, 1));
          jSpinner1.setName("jSpinner1"); // NOI18N
          //jPanel1.add(jSpinner1);

          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 1;
          gridBagConstraints.gridy = 3;
          getContentPane().add(jPanel1, gridBagConstraints);

          jPanel2.setName("jPanel2"); // NOI18N


          jLabel9.setName("jLabel9"); // NOI18N
          jPanel2.add(jLabel9);

          jSpinner6.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
          jSpinner6.setName("jSpinner6"); // NOI18N
          jPanel2.add(jSpinner6);


          jLabel10.setName("jLabel10"); // NOI18N
          jPanel2.add(jLabel10);

          jSpinner7.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
          jSpinner7.setName("jSpinner7"); // NOI18N
          jPanel2.add(jSpinner7);


          jLabel11.setName("jLabel11"); // NOI18N
          jPanel2.add(jLabel11);

          jSpinner8.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
          jSpinner8.setName("jSpinner8"); // NOI18N
          jPanel2.add(jSpinner8);


          jLabel12.setName("jLabel12"); // NOI18N
          jPanel2.add(jLabel12);

          jSpinner9.setModel(new javax.swing.SpinnerNumberModel(2009, 2000, 2020, 1));
          jSpinner9.setName("jSpinner9"); // NOI18N
          jPanel2.add(jSpinner9);

          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 1;
          gridBagConstraints.gridy = 1;
          getContentPane().add(jPanel2, gridBagConstraints);


          jLabel13.setName("jLabel13"); // NOI18N
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 0;
          gridBagConstraints.gridy = 2;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
          getContentPane().add(jLabel13, gridBagConstraints);

          jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
          jComboBox1.setName("jComboBox1"); // NOI18N
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 1;
          gridBagConstraints.gridy = 4;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
          getContentPane().add(jComboBox1, gridBagConstraints);

          jPanel3.setName("jPanel3"); // NOI18N

          buttonGroup1.add(jRadioButton1);

          jRadioButton1.setName("jRadioButton1"); // NOI18N
          jPanel3.add(jRadioButton1);

          buttonGroup1.add(jRadioButton2);

          jRadioButton2.setName("jRadioButton2"); // NOI18N
          jPanel3.add(jRadioButton2);

          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 1;
          gridBagConstraints.gridy = 2;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
          getContentPane().add(jPanel3, gridBagConstraints);


          jLabel14.setName("jLabel14"); // NOI18N
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 0;
          gridBagConstraints.gridy = 5;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
          getContentPane().add(jLabel14, gridBagConstraints);

          jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
          jComboBox2.setName("jComboBox2"); // NOI18N
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 1;
          gridBagConstraints.gridy = 5;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
          getContentPane().add(jComboBox2, gridBagConstraints);

          jPanel4.setName("jPanel4"); // NOI18N


          jButton2.setName("jButton2"); // NOI18N
          jButton2.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
               }
          });
          jPanel4.add(jButton2);


          jButton1.setName("jButton1"); // NOI18N
          jButton1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
               }
          });
          jPanel4.add(jButton1);

          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 1;
          gridBagConstraints.gridy = 6;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
          getContentPane().add(jPanel4, gridBagConstraints);

          pack();
     }// </editor-fold>//GEN-END:initComponents
     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	  // TODO add your handling code here:
	  this.setVisible(false);
	  this.setDefaultCloseOperation(this.HIDE_ON_CLOSE);
	  this.action = "CLOSE";
     }//GEN-LAST:event_jButton1ActionPerformed

     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
	  // TODO add your handling code here:
	  try {
	       //parsovanie dni
	       int retval = Integer.parseInt(this.jSpinner7.getValue().toString());
	       if (retval < 1 || retval > 31) {
		    JOptionPane.showMessageDialog(new javax.swing.JFrame(), "Invalid date!", "Error", JOptionPane.ERROR_MESSAGE);
		    return;
	       }
	       EventDays = retval;
	       //parsovanie hodin
	       retval = Integer.parseInt(this.jSpinner6.getValue().toString());
	       if (retval < 0 || retval > 23) {
		    JOptionPane.showMessageDialog(new javax.swing.JFrame(), "Invalid date!", "Error", JOptionPane.ERROR_MESSAGE);
		    return;
	       }
	       EventHours = retval;
	       //parsovanie mesiacov 
	       retval = Integer.parseInt(this.jSpinner8.getValue().toString());
	       if (retval < 1 || retval > 12) {
		    JOptionPane.showMessageDialog(new javax.swing.JFrame(), "Invalid date!", "Error", JOptionPane.ERROR_MESSAGE);
		    return;
	       }
	       EventMonths = retval;
	       retval = Integer.parseInt(this.jSpinner9.getValue().toString());
	       if (retval < 2000 || retval > 2020) {
		    JOptionPane.showMessageDialog(new javax.swing.JFrame(), "Invalid date!", "Error", JOptionPane.ERROR_MESSAGE);
		    return;
	       }
	       EventYears = retval;
	       //parsovanie dni intervalu 
	       retval = Integer.parseInt(this.jSpinner4.getValue().toString());
	       /**
	       if (retval < 0 || retval > 31) {
		    JOptionPane.showMessageDialog(new javax.swing.JFrame(), "Invalid date!", "Error", JOptionPane.ERROR_MESSAGE);
		    return;
	       }**/
	       intervalDays = retval;
	       //parsovanie hodin intervalu 
	       /**retval = Integer.parseInt(this.jSpinner2.getValue().toString());
	       if (retval < 1 || retval > 23) {
		    JOptionPane.showMessageDialog(new javax.swing.JFrame(), "Invalid date!", "Error", JOptionPane.ERROR_MESSAGE);
		    return;
	       }**/
	       intervalHours = retval;
	       //parsovanie mesiacov intervalu
	       retval = Integer.parseInt(this.jSpinner3.getValue().toString());
	       /**if (retval < 0 || retval > 11) {
		    JOptionPane.showMessageDialog(new javax.swing.JFrame(), "Invalid date!", "Error", JOptionPane.ERROR_MESSAGE);
		    return;
	       }**/
	       intervalMonths = retval;
	       retval = Integer.parseInt(this.jSpinner1.getValue().toString());/**
	       if (retval < 0) {
		    JOptionPane.showMessageDialog(new javax.swing.JFrame(), "Invalid date!", "Error", JOptionPane.ERROR_MESSAGE);
		    return;
	       }**/
	       intervalYears = retval;






	  } catch (NumberFormatException nfe) {
	       JOptionPane.showMessageDialog(new javax.swing.JFrame(), "Invalid date!", "Error", JOptionPane.ERROR_MESSAGE);
	       return;

	  }

        if ( this.jTextField2.getText().indexOf(' ') != -1 )
        {
		    JOptionPane.showMessageDialog(new javax.swing.JFrame(), "Group event name contains whitespaces", "Error", JOptionPane.ERROR_MESSAGE);
		    return;
        }


	  this.action = "CONFIRM";
	  this.setVisible(false);
     }//GEN-LAST:event_jButton2ActionPerformed


     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.ButtonGroup buttonGroup1;
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton2;
     private javax.swing.JComboBox jComboBox1;
     private javax.swing.JComboBox jComboBox2;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel10;
     private javax.swing.JLabel jLabel11;
     private javax.swing.JLabel jLabel12;
     private javax.swing.JLabel jLabel13;
     private javax.swing.JLabel jLabel14;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel8;
     private javax.swing.JLabel jLabel9;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JPanel jPanel3;
     private javax.swing.JPanel jPanel4;
     private javax.swing.JRadioButton jRadioButton1;
     private javax.swing.JRadioButton jRadioButton2;
     private javax.swing.JSpinner jSpinner1;
     private javax.swing.JSpinner jSpinner2;
     private javax.swing.JSpinner jSpinner3;
     private javax.swing.JSpinner jSpinner4;
     private javax.swing.JSpinner jSpinner6;
     private javax.swing.JSpinner jSpinner7;
     private javax.swing.JSpinner jSpinner8;
     private javax.swing.JSpinner jSpinner9;
     private javax.swing.JTextField jTextField2;
     // End of variables declaration//GEN-END:variables
     private String group;
     private String action = "";
     private int EventDays;
     private int EventHours;
     private int EventMonths;
     private int EventYears;
     private int intervalYears;
     private int intervalHours;
     private int intervalDays;
     private int intervalMonths;

     public String getAction() {
	  return this.action;

     }

    public String getGroupName()
    {
      return (String) this.jComboBox2.getSelectedItem() ;
    }
  
     public boolean isRepeatable() {
	  if (this.jRadioButton1.isSelected()) {
	       return true;
	  } else {
	       return false;
	  }
     }

     public String getEventName() {
	  return this.jTextField2.getText();
     }

     public int getCategory() {
	  if (this.jComboBox1.getSelectedIndex() == 0) {
	       return 101;
	  } else if (this.jComboBox1.getSelectedIndex() == 1) {
	       return 102;
	  } else if (this.jComboBox1.getSelectedIndex() == 2) {
	       return 103;
	  } else if (this.jComboBox1.getSelectedIndex() == 3) {
	       return 104;
	  } else {
	       return -1;
	  }
     }

     public int getEventDays() {
	  return EventDays;
     }

     public int getEventHours() {
	  return EventHours;
     }

     public int getEventMonths() {
	  return EventMonths;
     }

     public int getEventYears() {
	  return EventYears;
     }

     public int getOftenDays() {
	  return intervalDays;
     }

     public int getOftenHours() {
	  return intervalHours;
     }

     public int getOftenMonths() {
	  return intervalMonths;
     }

     public int getOftenYears() {
	  return intervalYears;
     }
}
