/*
 * LoginOrRegister.java
 *
 * Created on 27. duben 2009, 14:57
 */
package dialogs;

/**
 *
 * @author  ivo
 */
public class LoginOrRegister extends javax.swing.JDialog {

     /** Creates new form LoginOrRegister */
     public LoginOrRegister(java.awt.Frame parent, boolean modal) {
	  super(parent, modal);
	  initComponents();
     }

     /** This method is called from within the constructor to
      * initialize the form.
      * WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {
          java.awt.GridBagConstraints gridBagConstraints;

          jLabel1 = new javax.swing.JLabel();
          jTextField1 = new javax.swing.JTextField();
          jLabel2 = new javax.swing.JLabel();
          jPasswordField1 = new javax.swing.JPasswordField();
          jButton1 = new javax.swing.JButton();
          jButton2 = new javax.swing.JButton();
          jButton3 = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
          setTitle("Login"); // NOI18N
          setAlwaysOnTop(true);
          setName("logindialog"); // NOI18N
          setResizable(false);
          getContentPane().setLayout(new java.awt.GridBagLayout());

          jLabel1.setText("Login"); // NOI18N
          jLabel1.setName("jLabel1"); // NOI18N
          getContentPane().add(jLabel1, new java.awt.GridBagConstraints());

          jTextField1.setText(""); // NOI18N
          jTextField1.setName("jTextField1"); // NOI18N
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 1;
          gridBagConstraints.gridy = 0;
          gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
          getContentPane().add(jTextField1, gridBagConstraints);

          jLabel2.setText("Password"); // NOI18N
          jLabel2.setName("jLabel2"); // NOI18N
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 0;
          gridBagConstraints.gridy = 1;
          getContentPane().add(jLabel2, gridBagConstraints);

          jPasswordField1.setText(""); // NOI18N
          jPasswordField1.setName("jPasswordField1"); // NOI18N
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 1;
          gridBagConstraints.gridy = 1;
          gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
          getContentPane().add(jPasswordField1, gridBagConstraints);

          jButton1.setText("Login"); // NOI18N
          jButton1.setName("jButton1"); // NOI18N
          jButton1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
               }
          });
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 0;
          gridBagConstraints.gridy = 2;
          getContentPane().add(jButton1, gridBagConstraints);

          jButton2.setText("Register"); // NOI18N
          jButton2.setName("jButton2"); // NOI18N
          jButton2.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
               }
          });
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 1;
          gridBagConstraints.gridy = 2;
          getContentPane().add(jButton2, gridBagConstraints);

          jButton3.setText("Cancel"); // NOI18N
          jButton3.setName("jButton3"); // NOI18N
          jButton3.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
               }
          });
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 1;
          gridBagConstraints.gridy = 3;
          gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
          getContentPane().add(jButton3, gridBagConstraints);

          pack();
     }// </editor-fold>//GEN-END:initComponents
     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	  // TODO add your handling code here:
	  this.setVisible(false);
	  this.action = "LOGIN";
     }//GEN-LAST:event_jButton1ActionPerformed

     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
	  // TODO add your handling code here:
	  this.setVisible(false);
	  this.action = "REGISTRATION";
     }//GEN-LAST:event_jButton2ActionPerformed

     private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
	  // TODO add your handling code here:
	   this.setVisible(false);
	   this.action = "CANCEL";
     }//GEN-LAST:event_jButton3ActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
	  java.awt.EventQueue.invokeLater(new Runnable() {

	       public void run() {
		    LoginOrRegister dialog = new LoginOrRegister(new javax.swing.JFrame(), true);
		    dialog.addWindowListener(new java.awt.event.WindowAdapter() {

			 public void windowClosing(java.awt.event.WindowEvent e) {
			      System.exit(0);
			 }
		    });
		    dialog.setVisible(true);
	       }
	  });
     }
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton2;
     private javax.swing.JButton jButton3;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JPasswordField jPasswordField1;
     private javax.swing.JTextField jTextField1;
     // End of variables declaration//GEN-END:variables
     
     private String action;
     public String getAction(){
	  return action;
     }
     public String getLogin() {
	  return this.jTextField1.getText();
     }

     public String getPassword() {
	  return this.jPasswordField1.getPassword().toString();
     }
}
