/*
 * ViewAlert.java
 *
 * Created on 27. duben 2009, 17:07
 */

package dialogs;

import java.util.*;
import client.*;
import COMMON.*;
import java.util.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.table.*;
import javax.swing.border.*;

public class ViewAlert extends javax.swing.JDialog {
     
     /** Creates new form ViewAlert */
     public ViewAlert(java.awt.Frame parent, boolean modal, Date started, boolean repeatable,long interval) {
	  super(parent, modal);
	  initComponents();
          jLabel1.setText("Details of alert:");
          jLabel2.setText("Date:");
          jLabel3.setText("Interval:");
          jLabel4.setText("Repeatable:");
          jLabel5.setText(started.toString());
          jLabel6.setText(""+repeatable);
          jLabel8.setText(""+interval);
          jButton1.setText("Close");

	pack();
     }
     
     /** This method is called from within the constructor to
      * initialize the form.
      * WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {
          java.awt.GridBagConstraints gridBagConstraints;

          jLabel7 = new javax.swing.JLabel();
          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          jLabel6 = new javax.swing.JLabel();
          jLabel8 = new javax.swing.JLabel();
          jButton1 = new javax.swing.JButton();



          jLabel7.setName("jLabel7"); // NOI18N

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
          setName("Form"); // NOI18N
          getContentPane().setLayout(new java.awt.GridBagLayout());


          jLabel1.setName("jLabel1"); // NOI18N
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
          getContentPane().add(jLabel1, gridBagConstraints);


          jLabel2.setName("jLabel2"); // NOI18N
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 0;
          gridBagConstraints.gridy = 1;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
          getContentPane().add(jLabel2, gridBagConstraints);


          jLabel3.setName("jLabel3"); // NOI18N
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 0;
          gridBagConstraints.gridy = 3;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
          getContentPane().add(jLabel3, gridBagConstraints);


          jLabel4.setName("jLabel4"); // NOI18N
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 0;
          gridBagConstraints.gridy = 2;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
          getContentPane().add(jLabel4, gridBagConstraints);


          jLabel5.setName("jLabel5"); // NOI18N
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 1;
          gridBagConstraints.gridy = 2;
          getContentPane().add(jLabel5, gridBagConstraints);


          jLabel6.setName("jLabel6"); // NOI18N
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 1;
          gridBagConstraints.gridy = 1;
          getContentPane().add(jLabel6, gridBagConstraints);


          jLabel8.setName("jLabel8"); // NOI18N
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 1;
          gridBagConstraints.gridy = 3;
          getContentPane().add(jLabel8, gridBagConstraints);


          jButton1.setName("jButton1"); // NOI18N
          jButton1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
               }
          });
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 1;
          gridBagConstraints.gridy = 4;
          getContentPane().add(jButton1, gridBagConstraints);

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	  // TODO add your handling code here:
	  //CLOSE
	  this.setVisible(false);
	  this.setDefaultCloseOperation(this.HIDE_ON_CLOSE);
     }//GEN-LAST:event_jButton1ActionPerformed
     
     
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton jButton1;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel8;
     // End of variables declaration//GEN-END:variables
     
}
