/*
 * Register.java
 *
 * Created on 28. duben 2009, 19:34
 */
package dialogs;

import javax.swing.JOptionPane;

/**
 *
 * @author  ivo
 */
public class Register extends javax.swing.JDialog {

     /** Creates new form Register */
     public Register(java.awt.Frame parent, boolean modal) {
	  super(parent, modal);
	  initComponents();
	  this.jLabel1.setText("Login:");
	  this.jLabel2.setText("Surname:");
	  this.jLabel3.setText("Name:");
	  this.jLabel4.setText("Password:");
	  this.jTextField1.setText("");
	  this.jTextField2.setText("");
	  this.jTextField3.setText("");
	  this.jPasswordField1.setText("");
	  this.jButton1.setText("Confirm");
	  this.jButton2.setText("Close");



	  pack();
     }

     /** This method is called from within the constructor to
      * initialize the form.
      * WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {
          java.awt.GridBagConstraints gridBagConstraints;

          jLabel1 = new javax.swing.JLabel();
          jTextField1 = new javax.swing.JTextField();
          jLabel2 = new javax.swing.JLabel();
          jTextField2 = new javax.swing.JTextField();
          jLabel3 = new javax.swing.JLabel();
          jTextField3 = new javax.swing.JTextField();
          jLabel4 = new javax.swing.JLabel();
          jPasswordField1 = new javax.swing.JPasswordField();
          jButton1 = new javax.swing.JButton();
          jButton2 = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
          setName("Form"); // NOI18N
          getContentPane().setLayout(new java.awt.GridBagLayout());



          jLabel1.setName("jLabel1"); // NOI18N
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
          getContentPane().add(jLabel1, gridBagConstraints);


          jTextField1.setName("jTextField1"); // NOI18N
          jTextField1.setPreferredSize(new java.awt.Dimension(120, 23));
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
          getContentPane().add(jTextField1, gridBagConstraints);


          jLabel2.setName("jLabel2"); // NOI18N
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 0;
          gridBagConstraints.gridy = 1;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
          getContentPane().add(jLabel2, gridBagConstraints);


          jTextField2.setName("jTextField2"); // NOI18N
          jTextField2.setPreferredSize(new java.awt.Dimension(120, 23));
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 1;
          gridBagConstraints.gridy = 1;
          gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
          getContentPane().add(jTextField2, gridBagConstraints);


          jLabel3.setName("jLabel3"); // NOI18N
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 0;
          gridBagConstraints.gridy = 2;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
          getContentPane().add(jLabel3, gridBagConstraints);


          jTextField3.setName("jTextField3"); // NOI18N
          jTextField3.setPreferredSize(new java.awt.Dimension(120, 23));
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 1;
          gridBagConstraints.gridy = 2;
          gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
          getContentPane().add(jTextField3, gridBagConstraints);


          jLabel4.setName("jLabel4"); // NOI18N
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 0;
          gridBagConstraints.gridy = 3;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
          getContentPane().add(jLabel4, gridBagConstraints);


          jPasswordField1.setName("jPasswordField1"); // NOI18N
          jPasswordField1.setPreferredSize(new java.awt.Dimension(120, 23));
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 1;
          gridBagConstraints.gridy = 3;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
          getContentPane().add(jPasswordField1, gridBagConstraints);


          jButton1.setName("jButton1"); // NOI18N
          jButton1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
               }
          });
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 0;
          gridBagConstraints.gridy = 4;
          getContentPane().add(jButton1, gridBagConstraints);


          jButton2.setName("jButton2"); // NOI18N
          jButton2.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
               }
          });
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 1;
          gridBagConstraints.gridy = 4;
          getContentPane().add(jButton2, gridBagConstraints);

          pack();
     }// </editor-fold>//GEN-END:initComponents
     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
	  // TODO add your handling code here:
	  //CLOSE
	  this.action = "CLOSE";
	  this.setVisible(false);
	  this.setDefaultCloseOperation(this.HIDE_ON_CLOSE);
     }//GEN-LAST:event_jButton2ActionPerformed

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	  // TODO add your handling code here:
	  //confirm
	  if (jTextField1.getText().toString().length() == 0 || jTextField2.getText().toString().length() == 0 || jTextField3.getText().toString().length() == 0 || this.jPasswordField1.getText().length() == 0)  {
	       JOptionPane.showMessageDialog(new javax.swing.JFrame(), "All fields have to be filled!", "Error", JOptionPane.ERROR_MESSAGE);
	       return;
	  }
	  
        if ( this.jTextField1.getText().indexOf(' ') != -1 )
        {
		    JOptionPane.showMessageDialog(new javax.swing.JFrame(), "Field contains whitespaces", "Error", JOptionPane.ERROR_MESSAGE);
		    return;
        }
        
        if ( this.jTextField2.getText().indexOf(' ') != -1 )
        {
		    JOptionPane.showMessageDialog(new javax.swing.JFrame(), "Field contains whitespaces", "Error", JOptionPane.ERROR_MESSAGE);
		    return;
        }
        
        if ( this.jTextField3.getText().indexOf(' ') != -1 )
        {
		    JOptionPane.showMessageDialog(new javax.swing.JFrame(), "Field contains whitespaces", "Error", JOptionPane.ERROR_MESSAGE);
		    return;
        }
        
        if ( this.jPasswordField1.getText().indexOf(' ') != -1 )
        {
		    JOptionPane.showMessageDialog(new javax.swing.JFrame(), "Field contains whitespaces", "Error", JOptionPane.ERROR_MESSAGE);
		    return;
        }                        	  
	  
	  this.action = "CONFIRM";
	  this.setVisible(false);
     }//GEN-LAST:event_jButton1ActionPerformed


     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton2;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JPasswordField jPasswordField1;
     private javax.swing.JTextField jTextField1;
     private javax.swing.JTextField jTextField2;
     private javax.swing.JTextField jTextField3;
     // End of variables declaration//GEN-END:variables
     private String action;

     public String getAction() {
	  return this.action;
     }
     public String getLogin(){
	  return this.jTextField1.getText();
     }
     public String getSurname(){
	  return this.jTextField2.getText();
     }
     public String getName(){
	  return this.jTextField3.getText();
     }
     public String getPassword(){
	  return jPasswordField1.getText();
     }
     
}
